/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  hero: {
    type: 'none' | 'heroTemplate1' | 'heroTemplate2';
    heroAlphaText?: string | null;
    backgroundImage?: (string | null) | Media;
    mobileBackgroundImage?: (string | null) | Media;
    enableBodyStyleSearch?: boolean | null;
    enablePriceSearch?: boolean | null;
    enableLocationSearch?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    height?: ('small' | 'medium' | 'large') | null;
    textAlignment?: ('left' | 'center' | 'right') | null;
    /**
     * Controls how visible the background image is (0 = hidden, 100 = fully visible)
     */
    overlayOpacity?: number | null;
    /**
     * Fallback gradient start color (hex)
     */
    gradientFrom?: string | null;
    /**
     * Fallback gradient end color (hex)
     */
    gradientTo?: string | null;
  };
  layout: (
    | CallToActionBlock
    | MediaBlock
    | StatsBarAlphaBlock
    | ContentBlock
    | ColumnsBlockType
    | HTMLBlock
    | SpacerBlock
    | ManufacturerLogoGridBlock
    | RibbonBannerBlock
    | ContentSectionBlock
    | ReviewsSectionBlock
    | ContainerSectionBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  title: string;
  slug: string;
  publishedAt?: string | null;
  /**
   * Select a parent page to create a hierarchy. Breadcrumbs will be automatically generated.
   */
  parent?: (string | null) | Page;
  enableBreadcrumb?: boolean | null;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarAlphaBlock".
 */
export interface StatsBarAlphaBlock {
  /**
   * Hex color code for the background
   */
  backgroundColor?: string | null;
  stats?:
    | {
        valueType: 'new-vehicles' | 'used-vehicles' | 'custom';
        /**
         * e.g., "1,234" or "+30,000"
         */
        value?: string | null;
        /**
         * e.g., "NEW VEHICLES"
         */
        label: string;
        /**
         * Internal link path, e.g., "/new-vehicles/"
         */
        link?: string | null;
        linkTarget?: ('_self' | '_blank') | null;
        linkRel?: ('follow' | 'nofollow' | 'nofollow noopener' | 'sponsored' | 'ugc') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBarAlpha';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Rich text content created with the WYSIWYG editor
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Auto-generated HTML from the editor (read-only)
   */
  htmlContent?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlockType".
 */
export interface ColumnsBlockType {
  columns?:
    | {
        size?: ('full' | 'twoThirds' | 'half' | 'oneThird' | 'oneQuarter') | null;
        blocks?:
          | (
              | CallToActionBlock
              | MediaBlock
              | StatsBarAlphaBlock
              | ContentBlock
              | HTMLBlock
              | SpacerBlock
              | ManufacturerLogoGridBlock
              | RibbonBannerBlock
              | ContentSectionBlock
              | ReviewsSectionBlock
              | FormBlock
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  gapSize?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
  verticalAlign?: ('start' | 'center' | 'end' | 'stretch') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columnsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HTMLBlock".
 */
export interface HTMLBlock {
  /**
   * Paste your HTML code here. Styles and scripts will be rendered.
   */
  htmlContent: string;
  /**
   * Allow script tags to execute (use with caution)
   */
  enableScripts?: boolean | null;
  /**
   * Wrap content in a container div for consistent page width
   */
  useContainer?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'htmlBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  /**
   * Select the amount of vertical space to add
   */
  size: 'small' | 'medium' | 'large' | 'xlarge';
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ManufacturerLogoGridBlock".
 */
export interface ManufacturerLogoGridBlock {
  /**
   * Number of columns in the grid (automatically responsive on mobile)
   */
  columns?: ('2' | '3' | '4' | '5' | '6') | null;
  /**
   * Optional: Enter a secondary dealer hostname (e.g., www.dealertower.com) to show only brands from that dealer that are NOT in the current dealer. Leave empty to show current dealer brands.
   */
  secondaryDealerHostname?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'manufacturerLogoGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RibbonBannerBlock".
 */
export interface RibbonBannerBlock {
  /**
   * Main text content of the banner (rich text supported)
   */
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Hex color code for gradient start (e.g., #72c6f5)
   */
  gradientFrom?: string | null;
  /**
   * Hex color code for gradient end (e.g., #5ab5e4)
   */
  gradientTo?: string | null;
  /**
   * Display downward pointing arrow below the banner
   */
  showArrow?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ribbonBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentSectionBlock".
 */
export interface ContentSectionBlock {
  /**
   * Main content text created with the WYSIWYG editor
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Auto-generated HTML from the editor (read-only)
   */
  htmlContent?: string | null;
  /**
   * Text alignment for the content
   */
  contentAlignment?: ('left' | 'center' | 'right') | null;
  /**
   * Vertical alignment when image is present
   */
  contentVerticalAlign?: ('start' | 'center' | 'end') | null;
  /**
   * Add expandable content that users can reveal with a "Show More" button
   */
  enableShowMore?: boolean | null;
  /**
   * Additional content revealed when user clicks "Show More"
   */
  expandedContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Auto-generated HTML from the expanded editor (read-only)
   */
  expandedHtmlContent?: string | null;
  /**
   * Custom text for the "Show More" button
   */
  showMoreButtonText?: string | null;
  /**
   * Custom text for the "Show Less" button
   */
  showLessButtonText?: string | null;
  /**
   * Style of the Show More/Less button
   */
  showMoreButtonStyle?: ('link' | 'primary' | 'secondary' | 'outline') | null;
  /**
   * Optional image (recommended: 500x400px or similar aspect ratio)
   */
  image?: (string | null) | Media;
  /**
   * Position of image relative to content
   */
  imagePosition?: ('left' | 'right') | null;
  /**
   * Enable for above-the-fold images (improves LCP)
   */
  imagePriority?: boolean | null;
  /**
   * Visual style for the image
   */
  imageStyle?: ('rounded' | 'circle' | 'square' | 'none') | null;
  /**
   * Shadow depth for the image
   */
  imageShadow?: ('none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl') | null;
  /**
   * Maximum width of the image
   */
  imageMaxWidth?: ('sm' | 'md' | 'lg' | 'full') | null;
  /**
   * Image position on mobile devices
   */
  mobileImagePosition?: ('top' | 'bottom' | 'hidden') | null;
  /**
   * Overall layout structure of the section
   */
  layout?: ('split' | 'full' | 'centered' | 'background') | null;
  /**
   * Maximum width for full/centered layout
   */
  contentWidth?: ('xl' | '2xl' | '3xl' | '4xl' | '7xl') | null;
  /**
   * Ratio between content and image columns
   */
  splitRatio?: ('50-50' | '60-40' | '40-60' | '70-30' | '30-70') | null;
  /**
   * Space between content and image
   */
  gapSize?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
  /**
   * Top padding (responsive)
   */
  paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl') | null;
  /**
   * Bottom padding (responsive)
   */
  paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl') | null;
  /**
   * Maximum width of the section container
   */
  maxWidth?: ('5xl' | '6xl' | '7xl' | 'full') | null;
  /**
   * Left and right padding
   */
  horizontalPadding?: ('none' | 'small' | 'default' | 'large') | null;
  /**
   * Hex color code for the background (or gradient start color)
   */
  backgroundColor?: string | null;
  /**
   * Enable gradient from start color to end color
   */
  isGradient?: boolean | null;
  /**
   * End color for gradient background
   */
  gradientEndColor?: string | null;
  /**
   * Direction of the gradient
   */
  gradientDirection?: ('to-b' | 'to-t' | 'to-r' | 'to-l' | 'to-br' | 'to-bl' | 'to-tr' | 'to-tl') | null;
  /**
   * Overlay opacity (useful with background images)
   */
  backgroundOverlay?: ('none' | 'light' | 'medium' | 'dark' | 'heavy') | null;
  ctas?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        /**
         * Where to position the CTA button
         */
        position?: ('content' | 'image') | null;
        /**
         * Visual style of the button
         */
        style?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link') | null;
        /**
         * Size of the button
         */
        size?: ('sm' | 'md' | 'lg') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Alignment of CTA buttons
   */
  ctaAlignment?: ('left' | 'center' | 'right') | null;
  /**
   * Space between CTA buttons
   */
  ctaSpacing?: ('sm' | 'md' | 'lg') | null;
  /**
   * Hide section on mobile (< 768px)
   */
  hideOnMobile?: boolean | null;
  /**
   * Hide section on tablet (768px - 1024px)
   */
  hideOnTablet?: boolean | null;
  /**
   * Hide section on desktop (> 1024px)
   */
  hideOnDesktop?: boolean | null;
  /**
   * Override text alignment on mobile
   */
  mobileTextAlign?: ('default' | 'left' | 'center' | 'right') | null;
  /**
   * Override top padding on mobile
   */
  mobilePaddingTop?: ('default' | 'none' | 'xs' | 'sm' | 'md' | 'lg') | null;
  /**
   * Override bottom padding on mobile
   */
  mobilePaddingBottom?: ('default' | 'none' | 'xs' | 'sm' | 'md' | 'lg') | null;
  /**
   * Optional ID attribute for anchor links
   */
  htmlId?: string | null;
  /**
   * Additional CSS classes for the section
   */
  customClasses?: string | null;
  /**
   * Additional CSS classes for the content area
   */
  contentCustomClasses?: string | null;
  /**
   * Animation when section comes into view
   */
  animationStyle?: ('none' | 'fadeIn' | 'slideUp' | 'slideLeft' | 'slideRight') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsSectionBlock".
 */
export interface ReviewsSectionBlock {
  /**
   * Main heading for the reviews section
   */
  sectionTitle?: string | null;
  showAverageRating?: boolean | null;
  /**
   * Average star rating to display
   */
  averageRating?: string | null;
  /**
   * Text displayed after the rating
   */
  ratingLabel?: string | null;
  styleSettings?: {
    /**
     * Main background color
     */
    backgroundColor?: string | null;
    /**
     * Stars, rating number, and decorative elements
     */
    accentColor?: string | null;
    /**
     * Section title text color
     */
    titleColor?: string | null;
    /**
     * Rating label text color
     */
    ratingLabelColor?: string | null;
    /**
     * Show blurred accent color circles in background
     */
    showDecorativeElements?: boolean | null;
  };
  cardSettings?: {
    cardBackgroundColor?: string | null;
    /**
     * Review text color
     */
    cardTextColor?: string | null;
    authorNameColor?: string | null;
    cardBorderRadius?: ('none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl') | null;
  };
  layoutSettings?: {
    /**
     * Number of reviews visible at once
     */
    reviewsPerPage?: number | null;
    gridColumns?: ('1' | '2' | '3') | null;
    paddingSize?: ('small' | 'medium' | 'large') | null;
  };
  /**
   * Add customer reviews to display
   */
  reviews?:
    | {
        author: string;
        rating: number;
        text: string;
        id?: string | null;
      }[]
    | null;
  paginationSettings?: {
    showPagination?: boolean | null;
    activeDotColor?: string | null;
    inactiveDotColor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviewsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * Select a form from Dealer Tower to display on this page
   */
  formId: string;
  /**
   * Wrap the form in a container div for consistent page width
   */
  useContainer?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerSectionBlock".
 */
export interface ContainerSectionBlock {
  /**
   * Add blocks inside this container section
   */
  blocks?:
    | (
        | CallToActionBlock
        | MediaBlock
        | StatsBarAlphaBlock
        | ContentBlock
        | ColumnsBlockType
        | HTMLBlock
        | SpacerBlock
        | ManufacturerLogoGridBlock
        | RibbonBannerBlock
        | ContentSectionBlock
        | ReviewsSectionBlock
        | FormBlock
      )[]
    | null;
  /**
   * Maximum width of the inner container
   */
  maxWidth?:
    | ('xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | '6xl' | '7xl' | 'full' | 'none')
    | null;
  /**
   * Horizontal padding inside the container
   */
  horizontalPadding?: ('none' | 'small' | 'default' | 'large' | 'xl') | null;
  /**
   * Center the container horizontally (mx-auto)
   */
  centerContent?: boolean | null;
  /**
   * Top padding of the section (responsive)
   */
  paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl') | null;
  /**
   * Bottom padding of the section (responsive)
   */
  paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl') | null;
  /**
   * Background color of the section
   */
  backgroundColor?: string | null;
  enableGradient?: boolean | null;
  /**
   * End color for gradient background
   */
  gradientEndColor?: string | null;
  /**
   * Direction of the gradient
   */
  gradientDirection?: ('to-b' | 'to-t' | 'to-r' | 'to-l' | 'to-br' | 'to-bl' | 'to-tr' | 'to-tl') | null;
  /**
   * Hide this section on mobile devices (< 768px)
   */
  hideOnMobile?: boolean | null;
  /**
   * Hide this section on tablet devices (768px - 1024px)
   */
  hideOnTablet?: boolean | null;
  /**
   * Hide this section on desktop devices (> 1024px)
   */
  hideOnDesktop?: boolean | null;
  /**
   * Override max width on mobile devices (< 768px)
   */
  mobileMaxWidth?: ('default' | 'full' | 'xs' | 'sm' | 'md' | 'lg') | null;
  /**
   * Override top padding on mobile devices (< 768px)
   */
  mobilePaddingTop?: ('default' | 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  /**
   * Override bottom padding on mobile devices (< 768px)
   */
  mobilePaddingBottom?: ('default' | 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  /**
   * Override horizontal padding on mobile devices (< 768px)
   */
  mobileHorizontalPadding?: ('default' | 'none' | 'xs' | 'sm' | 'md' | 'lg') | null;
  /**
   * Optional ID attribute for the section (useful for anchor links)
   */
  htmlId?: string | null;
  /**
   * Additional CSS classes to apply to the section wrapper
   */
  customClasses?: string | null;
  /**
   * Additional CSS classes to apply to the inner container
   */
  innerCustomClasses?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'containerSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        type?: T;
        heroAlphaText?: T;
        backgroundImage?: T;
        mobileBackgroundImage?: T;
        enableBodyStyleSearch?: T;
        enablePriceSearch?: T;
        enableLocationSearch?: T;
        title?: T;
        subtitle?: T;
        height?: T;
        textAlignment?: T;
        overlayOpacity?: T;
        gradientFrom?: T;
        gradientTo?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        statsBarAlpha?: T | StatsBarAlphaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        columnsBlock?: T | ColumnsBlockTypeSelect<T>;
        htmlBlock?: T | HTMLBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        manufacturerLogoGrid?: T | ManufacturerLogoGridBlockSelect<T>;
        ribbonBanner?: T | RibbonBannerBlockSelect<T>;
        contentSection?: T | ContentSectionBlockSelect<T>;
        reviewsSection?: T | ReviewsSectionBlockSelect<T>;
        containerSection?: T | ContainerSectionBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  title?: T;
  slug?: T;
  publishedAt?: T;
  parent?: T;
  enableBreadcrumb?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarAlphaBlock_select".
 */
export interface StatsBarAlphaBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  stats?:
    | T
    | {
        valueType?: T;
        value?: T;
        label?: T;
        link?: T;
        linkTarget?: T;
        linkRel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  content?: T;
  htmlContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlockType_select".
 */
export interface ColumnsBlockTypeSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        blocks?:
          | T
          | {
              cta?: T | CallToActionBlockSelect<T>;
              mediaBlock?: T | MediaBlockSelect<T>;
              statsBarAlpha?: T | StatsBarAlphaBlockSelect<T>;
              content?: T | ContentBlockSelect<T>;
              htmlBlock?: T | HTMLBlockSelect<T>;
              spacer?: T | SpacerBlockSelect<T>;
              manufacturerLogoGrid?: T | ManufacturerLogoGridBlockSelect<T>;
              ribbonBanner?: T | RibbonBannerBlockSelect<T>;
              contentSection?: T | ContentSectionBlockSelect<T>;
              reviewsSection?: T | ReviewsSectionBlockSelect<T>;
              formBlock?: T | FormBlockSelect<T>;
            };
        id?: T;
      };
  gapSize?: T;
  verticalAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HTMLBlock_select".
 */
export interface HTMLBlockSelect<T extends boolean = true> {
  htmlContent?: T;
  enableScripts?: T;
  useContainer?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ManufacturerLogoGridBlock_select".
 */
export interface ManufacturerLogoGridBlockSelect<T extends boolean = true> {
  columns?: T;
  secondaryDealerHostname?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RibbonBannerBlock_select".
 */
export interface RibbonBannerBlockSelect<T extends boolean = true> {
  text?: T;
  gradientFrom?: T;
  gradientTo?: T;
  showArrow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentSectionBlock_select".
 */
export interface ContentSectionBlockSelect<T extends boolean = true> {
  content?: T;
  htmlContent?: T;
  contentAlignment?: T;
  contentVerticalAlign?: T;
  enableShowMore?: T;
  expandedContent?: T;
  expandedHtmlContent?: T;
  showMoreButtonText?: T;
  showLessButtonText?: T;
  showMoreButtonStyle?: T;
  image?: T;
  imagePosition?: T;
  imagePriority?: T;
  imageStyle?: T;
  imageShadow?: T;
  imageMaxWidth?: T;
  mobileImagePosition?: T;
  layout?: T;
  contentWidth?: T;
  splitRatio?: T;
  gapSize?: T;
  paddingTop?: T;
  paddingBottom?: T;
  maxWidth?: T;
  horizontalPadding?: T;
  backgroundColor?: T;
  isGradient?: T;
  gradientEndColor?: T;
  gradientDirection?: T;
  backgroundOverlay?: T;
  ctas?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        position?: T;
        style?: T;
        size?: T;
        id?: T;
      };
  ctaAlignment?: T;
  ctaSpacing?: T;
  hideOnMobile?: T;
  hideOnTablet?: T;
  hideOnDesktop?: T;
  mobileTextAlign?: T;
  mobilePaddingTop?: T;
  mobilePaddingBottom?: T;
  htmlId?: T;
  customClasses?: T;
  contentCustomClasses?: T;
  animationStyle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsSectionBlock_select".
 */
export interface ReviewsSectionBlockSelect<T extends boolean = true> {
  sectionTitle?: T;
  showAverageRating?: T;
  averageRating?: T;
  ratingLabel?: T;
  styleSettings?:
    | T
    | {
        backgroundColor?: T;
        accentColor?: T;
        titleColor?: T;
        ratingLabelColor?: T;
        showDecorativeElements?: T;
      };
  cardSettings?:
    | T
    | {
        cardBackgroundColor?: T;
        cardTextColor?: T;
        authorNameColor?: T;
        cardBorderRadius?: T;
      };
  layoutSettings?:
    | T
    | {
        reviewsPerPage?: T;
        gridColumns?: T;
        paddingSize?: T;
      };
  reviews?:
    | T
    | {
        author?: T;
        rating?: T;
        text?: T;
        id?: T;
      };
  paginationSettings?:
    | T
    | {
        showPagination?: T;
        activeDotColor?: T;
        inactiveDotColor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  formId?: T;
  useContainer?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerSectionBlock_select".
 */
export interface ContainerSectionBlockSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        statsBarAlpha?: T | StatsBarAlphaBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        columnsBlock?: T | ColumnsBlockTypeSelect<T>;
        htmlBlock?: T | HTMLBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        manufacturerLogoGrid?: T | ManufacturerLogoGridBlockSelect<T>;
        ribbonBanner?: T | RibbonBannerBlockSelect<T>;
        contentSection?: T | ContentSectionBlockSelect<T>;
        reviewsSection?: T | ReviewsSectionBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  maxWidth?: T;
  horizontalPadding?: T;
  centerContent?: T;
  paddingTop?: T;
  paddingBottom?: T;
  backgroundColor?: T;
  enableGradient?: T;
  gradientEndColor?: T;
  gradientDirection?: T;
  hideOnMobile?: T;
  hideOnTablet?: T;
  hideOnDesktop?: T;
  mobileMaxWidth?: T;
  mobilePaddingTop?: T;
  mobilePaddingBottom?: T;
  mobileHorizontalPadding?: T;
  htmlId?: T;
  customClasses?: T;
  innerCustomClasses?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Select the header layout/theme to use
   */
  theme: 'alpha';
  /**
   * Custom logo for the header
   */
  logo?: (string | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        /**
         * Optional nested menu items (dropdown)
         */
        subItems?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'none') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show or hide the "Search vehicles" search box in the header.
   */
  showSearchBox?: boolean | null;
  /**
   * Configure the call-to-action button (e.g., "Contact Us"). Leave text empty to hide the button.
   */
  ctaButton?: {
    /**
     * Text to display on the button. Leave empty to hide the button.
     */
    text?: string | null;
    link?: {
      type?: ('reference' | 'custom' | 'none') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Select the footer layout/theme to use
   */
  theme: 'alpha';
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'none') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  theme?: T;
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        subItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  showSearchBox?: T;
  ctaButton?:
    | T
    | {
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  theme?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}